import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/navbar/navbar";

const DMSans = localFont({
  src: './fonts/DMSans-VariableFont_opszwght.ttf',
  variable: "--font-nilor",
  weight:"100 900"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${DMSans.variable} antialiased bg-nilor-black`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
